### ISSUE TITLE
show_hover without hotkeys

### ISSUE THREAD

**Issue by Mte90** [simrat39/symbols-outline.nvim#10]
I was thinking that `highlight_hovered_item` was showing the modal instead not when I move with the cursor the position.
It is possible to turn it when the item is highlight in the sidebar?
Also with a flag is not a problem (also for performance is not a problem too).

**Comment by simrat39** [comment]
I'm not sure if i understood what you meant, something like this?
![previewpreview](https://user-images.githubusercontent.com/37233846/116768452-81802600-a9eb-11eb-87a5-c6c5eaf161c9.gif)

**Comment by Mte90** [comment]
Yes something like this will be perfect! Looking at the readme I wasn't able to find how to do it, maybe I am missing something?

**Comment by simrat39** [comment]
It's still in the works as of now

**Comment by Mte90** [comment]
Ok so I will wait for that :-)

**Comment by simrat39** [comment]
@Mte90 Added it, still experimental-ish

auto_preview = true in your config
