### ISSUE TITLE
Symbol indent/hierarchy in Vue files

### ISSUE THREAD

**Issue by chuckmasucci** [simrat39/symbols-outline.nvim#103]
Would it be possible to have the symbols in a Vue file be in a tree/hierarchy similar to Lua files? Right now all symbols are at the same level, which makes navigating a bit difficult.

Vue symbols:
![image](https://user-images.githubusercontent.com/1163251/152034040-475d8c3e-9f3c-49be-a8aa-a841c7d573e4.png)

Lua symbols:
![image](https://user-images.githubusercontent.com/1163251/152034080-e730a131-5fba-493c-9639-c5156db043ec.png)

**Comment by captainko** [comment]
Can u recheck it? I see VSCode gets this right.

**Comment by SpicyChickenFLY** [comment]
I agree with @captainko, [barbecue.nvim](https://github.com/utilyre/barbecue.nvim) parse the indent/hierarchy correctly with LSP vuels. Can you check it again? @simrat39
