### ISSUE TITLE
:SymbolsOutline does nothing

### ISSUE THREAD

**Issue by Phosphorescentt** [simrat39/symbols-outline.nvim#107]
I'm using a fresh install of [NvChad](https://github.com/nvchad/nvchad) with only symbols outline added. Running `:SymbolsOutline` does nothing. I don't know which LSP I'm using as I'm quite new to properly configuring nvim let alone nvim with lua so sorry :sweat_smile: - everything should be in the NvChad repo though. Sorry I can't provide more details.

**Comment by simrat39** [comment]
you need a language server running, :LspInfo should tell you

**Comment by Phosphorescentt** [comment]
Turns out I didn't have a language server installed at all! Thanks for your time - sorry I couldn't figure this out myself :)
