### ISSUE TITLE
Consistent code styling

### ISSUE THREAD

**Issue by FollieHiyuki** [simrat39/symbols-outline.nvim#109]
As the project keeps gaining contributions, I think now is a good time to integrate `stylua` or `editorconfig` to enforce styling, so that the code base is consistent.

I can send a PR, but we should discuss what style you prefer (tabs vs spaces; ' or " for quotes, etc.)

**Comment by simrat39** [comment]
2 spaces + ' ' for quotes sounds good

**Comment by FollieHiyuki** [comment]
Closing since my PR got merged. Thanks :)
