### ISSUE TITLE
Can't change color of the highlighted symbols

### ISSUE THREAD

**Issue by 71GA** [simrat39/symbols-outline.nvim#127]
Is there any way I can change color of the highlighted symbols? I really don't like the default yellow color...
![Screenshot 2022-04-20 092232](https://user-images.githubusercontent.com/8915807/164173253-2e0a791a-4b1e-427f-a919-1ffe2bbe4cd0.png)

**Comment by FollieHiyuki** [comment]
See `:help symbols-outline-highlights`

**Comment by re1von** [comment]
To change the selection style, use: `:hi FocusedSymbol ...`
E.g.:
`:hi FocusedSymbol gui=bold guifg=#C678DD`

![image](https://user-images.githubusercontent.com/80891241/164992335-7bf0070a-8ee4-4f24-97fb-1998222a5bb6.png)


If not specified, used:
`:hi FocusedSymbol term=italic,bold cterm=italic ctermbg=yellow ctermfg=darkblue gui=bold,italic guibg=yellow guifg=darkblue`
