### ISSUE TITLE
auto_perview

### ISSUE THREAD

**Issue by Yan-weihao** [simrat39/symbols-outline.nvim#132]
Why do I turn off the automatic preview code, but it still previews automatically

**Comment by AryWZ11** [comment]
if you are using packer, you may need to run :PackerCompile to refresh the plugin/packer_compiled.lua

**Comment by YWHMatrix** [comment]
Thanks for your answers, finally it turned off the preview, although I didn't know it suddenly worked

**Comment by WhyNotHugo** [comment]
@YWHMatrix How did you manage to turn it off?

**Comment by par4m** [comment]
Experiencing the same thing, turned off auto preview but still getting it.

**Comment by WhyNotHugo** [comment]
This is still an issue for me; I can't use symbols-outline without getting the preview popups.

**Comment by jaredmcqueen** [comment]
samesies.  I keep running `PackerCompile` over and over and still it happens.  IMO the auto-preview, while pretty cool, should be defaulted to false.

**Comment by par4m** [comment]
> samesies. I keep running `PackerCompile` over and over and still it happens. IMO the auto-preview, while pretty cool, should be defaulted to false.

Yep it's broken, I've removed this plugin till auto preview is disabled

**Comment by WhyNotHugo** [comment]
So by applying this patch previews are not shown:

```
diff --git a/lua/symbols-outline.lua b/lua/symbols-outline.lua
index bf253d1..6c61fc5 100644
--- a/lua/symbols-outline.lua
+++ b/lua/symbols-outline.lua
@@ -17,7 +17,7 @@ local function setup_global_autocmd()
 end
 
 local function setup_buffer_autocmd()
-  if config.options.auto_preview then
+  if false then
     vim.cmd "au CursorHold <buffer> lua require'symbols-outline.preview'.show()"
   else
     vim.cmd "au CursorMoved <buffer> lua require'symbols-outline.preview'.close()"
```

So it seems that what is failing is that the flag from the `setup()` called isn't being stored in the internal config properly.

**Comment by simrat39** [comment]
So the thing is setup is called automatically [here](https://github.com/simrat39/symbols-outline.nvim/blob/master/plugin/symbols-outline.vim#L6) which is probably why your config isn't accepted. So if you setup your config like [this](https://github.com/simrat39/symbols-outline.nvim#configuration), then auto_preview should work as expected.

I am also working on a refactor of the plugin [here](https://github.com/simrat39/symbols-outline.nvim/tree/rework) which should disable auto_preview on its own

**Comment by simrat39** [comment]
Auto preview is disabled by default now
