### ISSUE TITLE
requirements unclear

### ISSUE THREAD

**Issue by gennaro-tedesco** [simrat39/symbols-outline.nvim#14]
The documentations states `A tree like view for symbols in Neovim using the Language Server Protocol. Supports all your favourite languages.`: does this mean that [nvim-lspconfig](https://github.com/neovim/nvim-lspconfig) is a prerequisite (it is not indicated as such)?

I have installed the plugin but nothing happens after invoking it, therefore I suppose I miss some dependencies that are not explicitly indicated, or am I wrong?

**Comment by phatsk** [comment]
Wondering about this too. I use [CoC](https://github.com/neoclide/coc.nvim) to interface with the Intelephense LSP and I don't see anything when I invoke this plugin.

**Comment by simrat39** [comment]
Yes, the inbuilt lsp is a requirement. I should make it more obvious in the readme

**Comment by gennaro-tedesco** [comment]
> Yes, the inbuilt lsp is a requirement. I should make it more obvious in the readme

Do you mean [https://github.com/neovim/nvim-lspconfig](https://github.com/neovim/nvim-lspconfig) then? Because this isn't "inbuilt", it is just a plugin to interface LSP (like others).

**Comment by simrat39** [comment]
> > Yes, the inbuilt lsp is a requirement. I should make it more obvious in the readme
> 
> Do you mean [nvim-lspconfig](https://github.com/neovim/nvim-lspconfig) then? Because this isn't the built-in, it is just a plugin to interface the built-in LSP (like others), the latter of which being shipped with neovim already.

No, i mean as long as the client is neovim's inbuilt lsp client, this plugin will work. Something like https://github.com/akinsho/flutter-tools.nvim will still work even though it does not use nvim-lspconfig because it sets up the lsp server using the inbuilt client, but something like coc wouldn't work because it has it's own client

**Comment by gennaro-tedesco** [comment]
Isn't the client activated by default by just having neovim, or must one activate it? In your example flutter-tools make use of plenary as requirement.

To rephrase the question: assuming a fresh installation of neovim > 0.5, what are the necessary steps to have the plugin working (could you provide a minimal reproducible example)?

**Comment by simrat39** [comment]
> Isn't the client activated by default by just having neovim, or must one activate it? In your example flutter-tools make use of plenary as requirement.
> 
> To rephrase the question: assuming a fresh installation of neovim > 0.5, what are the necessary steps to have the plugin working (could you provide a minimal reproducible example)?

You can think of nvim-lspconfig as a dependency, because 99% of people will be using that, but technically speaking, it's not a dependency, a lsp server running with neovim's builtin lsp client is (which is done by nvim-lspconfig)

**Comment by simrat39** [comment]
So anyways nvim-lspconfig is kind of a dependency, but we need a language server which uses neovim's inbuild LSP client
