### ISSUE TITLE
Filetype unknown

### ISSUE THREAD

**Issue by leoatchina** [simrat39/symbols-outline.nvim#141]
like #81 , I found it may be caused by confilicts with `nvim-treesitter`
[nvim-treesitter issue](https://github.com/nvim-treesitter/nvim-treesitter/issues/3075)

And I found this error  could be supressed by set `additional_vim_regex_highlighting = false` in hightlight section

**Comment by simrat39** [comment]
We no longer use regex based highlighting, so should be fixed.
