### ISSUE TITLE
After stopping an LSP, `symbols-outline` continuously errors

### ISSUE THREAD

**Issue by WhyNotHugo** [simrat39/symbols-outline.nvim#145]
If I run `:LspStop`, then `symbols-outline` will continuously error:

```
Error detected while processing CursorHold Autocommands for "<buffer=1>":                                                                    
method textDocument/documentSymbol is not supported by any of the servers registered for the current buffer
Press ENTER or type command to continue
```

Even if I remove `require("symbols-outline").setup({})` from my config, this continues happening (it seems the `autocmd` is set up at startup, and not via the `setup` call).

There's an `LspDetach` event, so I think `symbols-outline` could unregister its autocmd when the LSP is stopped with `:autocmd-remove` (though I've never actually used this TBH).

**Comment by WhyNotHugo** [comment]
Actually, `LspDetach` seems to only be available on `master`.

I'll try and move the `autocommand` into `setup()`, so at least there's a way to (temporarily) disable the plugin.

**Comment by simrat39** [comment]
Is this issue still there on https://github.com/simrat39/symbols-outline.nvim/tree/rework? Cant reproduce this on nvim 0.7

**Comment by simrat39** [comment]
Can't reproduce on 7d4050f716cc522dad3fbd2e2e9d1dfefd5f1ee9.

**Comment by WhyNotHugo** [comment]
I can still repro this, after running  `:LspStop` I still get continuous errors on `CursorHold`:

```
Error detected while processing CursorHold Autocommands for "<buffer=1>":                                                   
method textDocument/documentSymbol is not supported by any of the servers registered for the current buffer
```

Lemme double check that there's not another plugin that's causing this just in case.
