### ISSUE TITLE
Error E5108 attempt to index field 'view' (a nil value)  on opening symbols outline

### ISSUE THREAD

**Issue by ckybonist** [simrat39/symbols-outline.nvim#151]
After upgrade symbols-outline.nvim to e5b5e9e, run `:SymbolOutline` or `:SymbolOutlineOpen` will raise the error:

```
E5108: Error executing lua ...acker/start/symbols-outline.nvim/lua/symbols-outline.lua:227: attempt to index field 'view' (a nil value)
stack traceback:
        ...acker/start/symbols-outline.nvim/lua/symbols-outline.lua:227: in function 'open_outline'
        [string ":lua"]:1: in main chunk
```

**Comment by pitakill** [comment]
I've got a similar error, but in my case I wasn't referring correctly the plugin so with the correct name of the plugin the error is gone and everything is working as expected. My installation is from a couple of minutes ago and was a fresh install.

**Comment by shaksiper** [comment]
You need to setup the plugin by requiring as follows:
`require("symbols-outline").setup()`

**Comment by simrat39** [comment]
Yep, call the setup and the errors will be gone.
