### ISSUE TITLE
Error: attempt to index field 'view' 

### ISSUE THREAD

**Issue by piedpiper101** [simrat39/symbols-outline.nvim#154]
I update to the newest commit , and when i open symbols-outline, the vim prompt some errors.I guess maybe the folding feature has some problems?
<img width="1276" alt="screenshot" src="https://user-images.githubusercontent.com/75722438/185268937-70c752e7-462d-4e46-8506-71d7b830ab94.png">

**Comment by simrat39** [comment]
Pretty sure it's cause you're not calling setup. This was recently changed so see the setup part of the readme

**Comment by piedpiper101** [comment]
Yeah, it works after i calling setup, thanks.
