### ISSUE TITLE
E5108: Error executing lua

### ISSUE THREAD

**Issue by ftamhar** [simrat39/symbols-outline.nvim#155]
This morning (18 August 2022, UTC+8) I got this error after update `symbols-outline`.
The command that I execute is `:SymbolsOutline`

I open golang project.

`E5108: Error executing lua ...vim/plugged/symbols-outline.nvim/lua/symbols-outli
stack traceback:
        ...vim/plugged/symbols-outline.nvim/lua/symbols-outline.lua:307: in func
        [string ":lua"]:1: in main chunk`

**Comment by simrat39** [comment]
Pretty sure it's cause you're not calling setup. This was recently changed so see the setup part of the readme

**Comment by simrat39** [comment]
https://github.com/simrat39/symbols-outline.nvim#setup
