### ISSUE TITLE
Is it possible to auto-close the symbols window after selecting a symbol?

### ISSUE THREAD

**Issue by Integralist** [simrat39/symbols-outline.nvim#161]
Hello,

When I press `<Enter>` on one of the symbols in the window I'm taken directly to the symbol in the relevant file (as expected), but I'd also like the symbols window to be closed immediately afterwards. 

Currently, I have to manually execute a mapping that calls `:SymbolsOutlineClose`.

I'm not sure if there's an exposed event that I could hook into? If not, then I would like to propose a feature request for that if possible.

Many thanks!

**Comment by simrat39** [comment]
`auto_close` in config should do this.
https://github.com/simrat39/symbols-outline.nvim/blob/master/lua/symbols-outline/config.lua#L12

**Comment by Integralist** [comment]
Doh! I even went reading through the configuration before opening this issue. I don't know how I missed that. Sorry.
