### ISSUE TITLE
Open symbols outlie on specific filetype automatically

### ISSUE THREAD

**Issue by xbladesub** [simrat39/symbols-outline.nvim#179]
How to write correct autocommand (I think I should use this) to open symbols outline on specific filetype when buffer opens? Would be nice if can specify delay also

**Comment by jamestrew** [comment]
```lua
vim.api.nvim_create_autocmd("BufEnter", {
  pattern = { "*.py" },
  command = ":SymbolsOutlineOpen",
  group = vim.api.nvim_create_augroup("my_augroup", { clear = true }),
})
```
here's a starting point. honestly, I'm my limited testing it's pretty annoying and I wouldn't use it. Probably could tweak it to be much better but yeah... seems easier to just use a keybinding over handling a bunch of use/edge cases.
