### ISSUE TITLE
keymaps dont work

### ISSUE THREAD

**Issue by ViRu-ThE-ViRuS** [simrat39/symbols-outline.nvim#18]
Default Config (just installed the plugin)

Calling `:SymbolsOutline` opens up the right split, and shows the correct entries and fields and auto highlight works correctly with the icons and everything but the any keymap doesnt work, including `<cr>` or `r` or anything. Nor does the mouse click work. 

NVIM `v0.5.0-dev+1326-ge0a01bdf7`
LSP Server: `pylsp`

`:messages` is clean

**Comment by simrat39** [comment]
on NVIM v0.5.0-dev+1326-ge0a01bdf7
it seems to work fine for me

when you press enter, does it say something like this in the command menu?

![image](https://user-images.githubusercontent.com/37233846/119247621-f43e7600-bb3f-11eb-939d-b28f95dc764f.png)

**Comment by ViRu-ThE-ViRuS** [comment]
okay I figured it out that the following maps, break the symbols outline keymaps:

``` vim 
nnoremap ; :
nnoremap : ;
```

the way I fixed it was manually mapping symbols-outline commands using `nnoremap <buffer> ...`.

I wonder if making the mappings from the `keymaps` table in config to be non recursive?

**Comment by simrat39** [comment]
Yup making them non recursive should work, i tested it locally and seems to be working fine
