### ISSUE TITLE
Error on SymbolsOutlineOpen

### ISSUE THREAD

**Issue by gsalvatella** [simrat39/symbols-outline.nvim#189]
The following error shows up when issuing `:SymbolsOutlineOpen` in vim 0.8.0:

```bash
E5108: Error executing lua ...acker/start/symbols-outline.nvim/lua/symbols-outline.lua:307: attempt to index field 'view' (a nil value)                                            
stack traceback:
        ...acker/start/symbols-outline.nvim/lua/symbols-outline.lua:307: in function 'toggle_outline'
        [string ":lua"]:1: in main chunk
```

**Comment by renoinn** [comment]
same issue in nvim 0.9.0.

**Comment by gsalvatella** [comment]
I can confirm that the problem is the new configuration. This is a breaking change that should have been notified properly.

**Comment by gsalvatella** [comment]
@arthur-yatsun The `setup` method was introduced on August. Before that simple `vim` globals were used, but these are not working anymore. So even if you had it correctly set up you need to update to the new `setup` method. I'm closing the issue anyways.
