### ISSUE TITLE
Rust: doesn't show function params or `let __ = ...` symbols

### ISSUE THREAD

**Issue by ethanmsl** [simrat39/symbols-outline.nvim#195]
Images below of Rust where it shows larger structures (e.g. functions and impl blocks), but a `let foo = ...` doesn't result in `foo` being listed _nor_ are function parameters listed.  
By contrast, these seem to work normally in Lua and Python.

**Rust LSP**: Rust-Analyzer (and your own rust-tools plugin)
**Lua LSP**: Sumneko-Lua
**Python LSP**: Pyright

NVIM v0.8.2
Built type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@HMBRW-A-001-M1-005.local

## Rust (not as expected):
<img width="1006" alt="Rust (1) - SymbOutline" src="https://user-images.githubusercontent.com/33399972/210377290-75ef5612-72f9-4ca4-8351-3ac701186e2d.png">

<img width="1011" alt="Rust (2) - SymbOutline" src="https://user-images.githubusercontent.com/33399972/210377303-71e0a8f0-c156-4775-a151-073935b9eca6.png">

## Lua & Python (as expected)
<img width="902" alt="Lua - SymbOutline" src="https://user-images.githubusercontent.com/33399972/210371488-9dc71d90-ce4d-4795-a16a-f1ecf22423b5.png">

<img width="760" alt="Python - SymbOutline" src="https://user-images.githubusercontent.com/33399972/210374653-e6b7cd11-390f-4b01-bdbd-ab78299c2a52.png">

**Comment by simrat39** [comment]
Yeah this is a rust-analyzer thing, its just how they report symbols, we can't do anything about this
