### ISSUE TITLE
How to enable icon coloring?

### ISSUE THREAD

**Issue by mpas** [simrat39/symbols-outline.nvim#196]
I have installed the plugin into LunarVim. When I open the outline the icons appear to have no color. Other icons like the ones in treesittter are nicely colored. Any hint on how I can enable the colors?

![image](https://user-images.githubusercontent.com/139094/211760105-95dcfef1-2378-43e1-8d98-7cb4cef50e1b.png)

**Comment by jonarrien** [comment]
Not using LunarVim, but I guess it's missing the highlight groups defined by default. You can configure different ones in `symbols` section.

In my case, I had to change:
- `TSError` to `@error`
- `TSString` to `@string`
- `TSType` to `@type`
- etc.

You can check the available ones using `:highlight`.

**Comment by johnmathews** [comment]
I have the same issue, my hunch is that it isnt about undefined highlight groups, as icons in other outline plugins, and nvim-tree, are colored ok.

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/19152731/213303581-a1b02e40-eb5d-4d9b-89dd-d240bd6d8d4a.png">

**Comment by ehaynes99** [comment]
This is a change in treesitter that needs to be update in this library.

https://github.com/nvim-treesitter/nvim-treesitter/issues/2293#issuecomment-1279974776

> https://github.com/nvim-treesitter/nvim-treesitter/pull/3656 removed the obsolete TS* highlighting groups. Users and plugins should instead directly use the capture name as a highlight group. E.g., instead of
> 
> hi link TSPunctDelimit Delimiter
> do
> 
> hi link @punctuation.delimiter Delimiter

@johnmathews note that `nvim-tree` (and many others), use https://github.com/nvim-tree/nvim-web-devicons/blob/master/lua/nvim-web-devicons.lua These have distinct colors hardcoded, so not relying on treesitter.
