### ISSUE TITLE
BUG: The `width=40` option is not working correctly

### ISSUE THREAD

**Issue by linrongbin16** [simrat39/symbols-outline.nvim#231]
Hi, I'm setting `width=40` when setup, but it seems much wider in my screen.

<img width="1920" alt="image" src="https://github.com/simrat39/symbols-outline.nvim/assets/6496887/216a1c33-c6d5-4e19-a92b-d5eedb4b0507">

**Comment by hedyhli** [comment]
It looks like something made your code window and the outline window have equal width. Does it do that when you set width to something else or just 40?

**Comment by linrongbin16** [comment]
emmm, maybe, I switched to another plugin now...
