### ISSUE TITLE
Option to go to the current location when :SymbolsOutline is called

### ISSUE THREAD

**Issue by tmwatchanan** [simrat39/symbols-outline.nvim#24]
Is it possible to focus/go to the current location on the tree when we call `:SymbolsOutline`? Right now, once the outline is opened, it is always at the top most line.

**Comment by simrat39** [comment]
This should be the default behaviour, I don't think an option is needed

**Comment by pidgeon777** [comment]
I tried `:SymbolsOutline` but seems to be broken? (if **Symbols Outline** panel is already open, that command closes it instead of focusing on the symbol).
