### ISSUE TITLE
symbols-outline.nvim does not parse `impl trait` and its functions in Rust

### ISSUE THREAD

**Issue by plokid** [simrat39/symbols-outline.nvim#240]
I noticed that symbols-outline.nvim does not parse `impl trait` and its functions in Rust. This makes it difficult to navigate through the codebase. I have attached two screenshots for comparison. The first screenshot shows the symbols parsed by symbols-outline.nvim, while the second screenshot shows the symbols parsed by github. I think the latter one is better.

![20231111-154911](https://github.com/simrat39/symbols-outline.nvim/assets/72876162/c4205dc8-a991-44d4-91db-42bb5e0bef35)
.
![20231111-154922](https://github.com/simrat39/symbols-outline.nvim/assets/72876162/b0bb1032-542a-4489-8233-95d9ff34233a)

**Comment by hedyhli** [comment]
Unfortunately the symbols shown in the outline is determined by the provider (LSP/CoC). If you're using LSP, maybe that is all the information that the LSP provides?

**Comment by plokid** [comment]
OK, I found it's rust-analyzer problem. Thank you.

**Comment by plokid** [comment]
I found it problem is still there. rust-analyzer could provide the right information, like bellow
```bash
StructureNode { parent: None, label: "main", navigation_range: 3..7, node_range: 0..39, kind: SymbolKind(Function), 
detail: Some("fn()"), deprecated: false }
StructureNode { parent: None, label: "A", navigation_range: 65..66, node_range: 41..106, kind: SymbolKind(Struct), d
etail: None, deprecated: false }
StructureNode { parent: Some(1), label: "index1", navigation_range: 73..79, node_range: 73..86, kind: SymbolKind(Fie
ld), detail: Some("usize"), deprecated: false }
StructureNode { parent: Some(1), label: "index2", navigation_range: 92..98, node_range: 92..103, kind: SymbolKind(Fi
eld), detail: Some("i32"), deprecated: false }
StructureNode { parent: None, label: "impl A", navigation_range: 113..114, node_range: 108..209, kind: SymbolKind(Im
pl), detail: None, deprecated: false }
StructureNode { parent: Some(4), label: "new", navigation_range: 128..131, node_range: 121..207, kind: SymbolKind(Fu
nction), detail: Some("fn(index1: usize, index2: i32) -> Self"), deprecated: false }
```
It looks like `SymbolKind(Impl)` can not be handled correctly.

**Comment by hedyhli** [comment]
Could you share a source file with this issue so I can test it?

**Comment by plokid** [comment]
```rust
// src/main.rs
fn main() {
    let a = A::new(1, 2);
}

struct A {
    index1: usize,
    index2: i32,
}

impl A {
    pub fn new(index1: usize, index2: i32) -> Self {
        Self { index1, index2 }
    }
}

type B = u32;

static mut STATIC: usize = 0;

```
```bash
cat src/main.rs | rust-analyzer symbols
```

**Comment by hedyhli** [comment]
Btw before your comment I did a quick search and tried with this file: https://github.com/erikgrinaker/toydb/blob/master/src/client.rs

Here's what I get:

<img src="https://github.com/simrat39/symbols-outline.nvim/assets/50042066/bdcded04-9924-4727-97fc-812c6a54fb88" width=400>


And using the code you provided:

<img src="https://github.com/simrat39/symbols-outline.nvim/assets/50042066/78bc850d-2872-46cc-b47a-e424aa33a73f" width=400>

Note that I don't know rust, but it looks like symbols with `impl` are shown in both examples?

**Comment by plokid** [comment]
I use lazyvim, it looks like there are some custom configuration that make it really chaos. anyway, thank you.

**Comment by hedyhli** [comment]
Maybe it's the `symbols_blacklist`? By the way if you encounter other issues with symbols-outline.nvim, note that this plugin is no longer getting updates, so in that case you can instead try out my [fork](/hedyhli/outline.nvim) which might include a corresponding fix.
