### ISSUE TITLE
Error when calling SymbolsOutline

### ISSUE THREAD

**Issue by ovikk13** [simrat39/symbols-outline.nvim#25]
NVIM-version: `NVIM v0.5.0-dev+1384-gf2906a466`
Using latest version of symbols-outline.nvim

Calling SymbolsOutline in a PHP file throws the following error: 
`Error executing vim.schedule lua callback: .../packer/opt/symbols-outline.nvim/lua/symbols-outline.lua:188: Failed to rename buffer`

SymbolsOutline works fine in lua files.

**Comment by simrat39** [comment]
Does this happen with all php files?

**Comment by ovikk13** [comment]
Almost all php files. It has only worked with one php file so far. Though I do not see any reasons to why that file worked.

**Comment by spencerwi** [comment]
I've observed this also. I'm using intelephense as the language server in particular.

**Comment by simrat39** [comment]
Seems to work fine on https://github.com/banago/simple-php-website, can you guys give me an example project where its broken? Also make sure youre on the latest neovim version

**Comment by ovikk13** [comment]
I managed to reproduce the error using a php file with this content.
```php
<?php
class Hello {
    protected $data;

    public function test() {
    }
}
```

However the error only occurred when the intelephense language server was attatched to the buffer. I'm using neovim's native lsp client.

I updated just now (both neovim and plugins), and got the same issue.

Thanks for your help! :)

**Comment by ovikk13** [comment]
After further debugging, I realize this is the cause of multiple language servers. I have both intelephense and diagnostic language server running for the same buffer.

As `M.open_outline()` in `symbols-outline.lua:188` calls buf_request, the `handler` will be called for each result from every server. This causes multiple buffers to be opened, and `nvim_buf_set_name` to fail.

Therefore I'm closing this as a duplicate of #12
