### ISSUE TITLE
error after fresh installation

### ISSUE THREAD

**Issue by alexzanderr** [simrat39/symbols-outline.nvim#26]
i have 
```
Plug 'https://github.com/simrat39/symbols-outline.nvim'
```
plus many other plugins

but when i open nvim i get this error:
![Screenshot_2021-06-10_18-33-51](https://user-images.githubusercontent.com/54772464/121554713-0f075a80-ca1b-11eb-8e2f-2f082cf024b9.png)
ignore that part with deprecated nerdtree bla bla variable

here is the location of the error (`line 51`):
![image](https://user-images.githubusercontent.com/54772464/121555996-285cd680-ca1c-11eb-91d1-b616ef247caa.png)

i changed `M` to `local M` but it doesnt work anyway.

**Comment by simrat39** [comment]
Are you on the latest neovim? What's your neovim --version?

**Comment by simrat39** [comment]
Note that this plugin requires neovim 0,5 and utilizes the inbuilt lsp client

**Comment by alexzanderr** [comment]
upsyyyy. my bad.
i have 0.4.4

**Comment by alexzanderr** [comment]
should i do special configuration for LSP? or should i leave it as it is?

**Comment by alexzanderr** [comment]
now i installed nightly-vim (0.5) from AUR (im arch linux user)
i put this in my `init.vim`
```
" init.vim
let g:symbols_outline = {
    \ "highlight_hovered_item": v:true,
    \ "show_guides": v:true,
    \ "position": 'right',
    \ "auto_preview": v:true,
    \ "keymaps": {
        \ "close": "<Esc>",
        \ "goto_location": "<Cr>",
        \ "focus_location": "o",
        \ "hover_symbol": "<C-space>",
        \ "rename_symbol": "r",
        \ "code_actions": "a",
    \ },
    \ "lsp_blacklist": [],
\ }
```

when i open nvim, doesnt give my any errors.

when i type `:sym` and press `tab` i get `:SymbolsOutline`, so there is proof that the plugin is recognized by nvim, but when i press `enter` `nothing happens`.

any ideas?

**Comment by simrat39** [comment]
Well, this plugin needs a Language Server running in the background to display the symbols properly. Neovim 0.5 supports this but you need to actually set up the language server with something like https://github.com/neovim/nvim-lspconfig.
Maybe this video can help a bit with your understanding: https://www.youtube.com/watch?v=ArwDgvYEZYk

**Comment by alexzanderr** [comment]
okey then, how do i setup this `https://github.com/neovim/nvim-lspconfig` only for `symbols` outline only. because there are a lot of options and i dont think i need all of them. just tell me for symbols outline. please. i know that im a noob, but please teach me.

**Comment by alexzanderr** [comment]
this [video](https://www.youtube.com/watch?v=ArwDgvYEZYk) just tells you what a LSP is. in short, this video is useless

can you, at least, give me your "properly configured lsp" too see what im missing?

honestly, your documentation is crap. how do you expect me to understand from nothing to "properly configure an lsp" if i dont have strong background in neovim configurations. you can at least help me achieve that, im open to new stuff and i learn fast.

you make a plugin and you dont write proper documnetation for it to even be able to run it. good job @simrat39

**Comment by simrat39** [comment]
I'm not going to spoonfeed you your entire lsp configuration, that's something you have to do by yourself. I already linked nvim-lspconfig, the go to way of setting up language servers, you might wanna read their readme. It outlines everything you need tto set it up.
