### ISSUE TITLE
No treesitter highlight in preview

### ISSUE THREAD

**Issue by eruizc-dev** [simrat39/symbols-outline.nvim#27]
## No treesitter highligh in preview

As you can see in the following image, both are the exact same function. Left one is in active buffer and right one is in preview popup. The highlight is different because it's the popup is not using Treesitter.

![image](https://user-images.githubusercontent.com/58179604/121737988-f9a03800-cacf-11eb-90c6-859803f3eec9.png)

**Comment by simrat39** [comment]
This is because if we set a filetype in the hover window (to trigger tree-sitter), it causes the LSP to crash. A good solution would be to attach a tree-sitter parser to the buffer, so that's is a todo

**Comment by eruizc-dev** [comment]
I found this:

https://github.com/nvim-treesitter/nvim-treesitter/blob/8704b0f3882971a09a9c0e0bc1c95926bc304aea/lua/nvim-treesitter/configs.lua#L69-L73

It's called when you  do `:TSBufEnable`, I guess you can manually call this without changing filetype and executing a lot of autocmds like lsp

**Comment by eruizc-dev** [comment]
YEII! Didn't notice you updated this, so cool :D
