### ISSUE TITLE
Error when try to open in C++ header files

### ISSUE THREAD

**Issue by anuvyklack** [simrat39/symbols-outline.nvim#28]
Works in C++ source `.cpp` files, but throw an error when try to open in C++ header `.hpp` file:

```
Error executing vim.schedule lua callback: ...art/symbols-outline.nvim/lua/symbols-outline/symbols.lua:37: attempt to index a nil value
```

**Comment by simrat39** [comment]
This seems to work fine for me, can you provide a code sample on which its broken?
Also make sure youre on the latest version of the plugin

**Comment by GPN211314** [comment]
I found the reason
when I use clangd, it works
but it dose't works with ccls
cause the symbol ccls generated has kind "Unkown", while it can't be found in file symbols.lua
<img width="309" alt="截屏2021-07-12 下午3 35 38" src="https://user-images.githubusercontent.com/38633718/125250012-605f7e00-e328-11eb-8618-a5156555e8b1.png">
<img width="660" alt="截屏2021-07-12 下午3 35 21" src="https://user-images.githubusercontent.com/38633718/125250016-62294180-e328-11eb-82e4-b7d1a34db161.png">

**Comment by simrat39** [comment]
> I found the reason
> when I use clangd, it works
> but it dose't works with ccls
> cause the symbol ccls generated has kind "Unkown", while it can't be found in file symbols.lua
> <img alt="截屏2021-07-12 下午3 35 38" width="309" src="https://user-images.githubusercontent.com/38633718/125250012-605f7e00-e328-11eb-8618-a5156555e8b1.png">
> <img alt="截屏2021-07-12 下午3 35 21" width="660" src="https://user-images.githubusercontent.com/38633718/125250016-62294180-e328-11eb-82e4-b7d1a34db161.png">

Can you please give a code sample to test this on?

**Comment by GPN211314** [comment]
> > I found the reason
> > when I use clangd, it works
> > but it dose't works with ccls
> > cause the symbol ccls generated has kind "Unkown", while it can't be found in file symbols.lua
> > <img alt="截屏2021-07-12 下午3 35 38" width="309" src="https://user-images.githubusercontent.com/38633718/125250012-605f7e00-e328-11eb-8618-a5156555e8b1.png">
> > <img alt="截屏2021-07-12 下午3 35 21" width="660" src="https://user-images.githubusercontent.com/38633718/125250016-62294180-e328-11eb-82e4-b7d1a34db161.png">
> 
> Can you please give a code sample to test this on?

Just define a macro in cpp file, all the unkonwn items are macro

**Comment by simrat39** [comment]
> > > I found the reason
> > > when I use clangd, it works
> > > but it dose't works with ccls
> > > cause the symbol ccls generated has kind "Unkown", while it can't be found in file symbols.lua
> > > <img alt="截屏2021-07-12 下午3 35 38" width="309" src="https://user-images.githubusercontent.com/38633718/125250012-605f7e00-e328-11eb-8618-a5156555e8b1.png">
> > > <img alt="截屏2021-07-12 下午3 35 21" width="660" src="https://user-images.githubusercontent.com/38633718/125250016-62294180-e328-11eb-82e4-b7d1a34db161.png">
> > 
> > 
> > Can you please give a code sample to test this on?
> 
> Just define a macro in cpp file, all the unkonwn items are macro

Thanks, I can reproduce this with ccls and macros

**Comment by buptUnixGuys** [comment]
i also have the same problem. plugin version
commit 034792838579c4b1515c8a5037aba58ecd1d9b35 (HEAD -> master, origin/master, origin/HEAD)

**Comment by hydroakri** [comment]
![image](https://user-images.githubusercontent.com/24475059/187033985-279496bb-ca48-4d31-8633-1e7c42d19b9d.png)
same question when using ccls

**Comment by hawkinchina** [comment]
define a macro in .h file, all the unkonwn items are macro. 
eg. list.h
#define List_count(A) ((A)->count)

I meet the this problem.
the List_count() cannot be displayed in the outline window.
