### ISSUE TITLE
Window width issue after reopen nvim-tree

### ISSUE THREAD

**Issue by hungrybirder** [simrat39/symbols-outline.nvim#33]
commit: 631a8880deccf97bfea44d02d70afc8084f49c24

1. Open outline
2. Open nvim-tree
3. Close nvim-tree

Step 2&3 the outline window's width is not fixed but increased.

![image](https://user-images.githubusercontent.com/1021047/123068512-8b029900-d444-11eb-9163-98e26efb4c0d.png)
![image](https://user-images.githubusercontent.com/1021047/123068607-9e156900-d444-11eb-8227-0849703d3018.png)
![image](https://user-images.githubusercontent.com/1021047/123068658-aa012b00-d444-11eb-8dba-90c5816f168b.png)

**Comment by simrat39** [comment]
I think this is more of a nvim-tree issue, because it resizes any other split, not just symbols-outline

**Comment by hungrybirder** [comment]
> I think this is more of a nvim-tree issue, because it resizes any other split, not just symbols-outline

I tested it with [nerdtree](https://github.com/preservim/nerdtree) and I got the same issue.

**Comment by simrat39** [comment]
> > I think this is more of a nvim-tree issue, because it resizes any other split, not just symbols-outline
> 
> I tested it with [nerdtree](https://github.com/preservim/nerdtree) and I got the same issue.

It works fine on nerdtree for me
![Peek 2021-06-28 13-14](https://user-images.githubusercontent.com/37233846/123699097-ba821e80-d813-11eb-8ce4-fdf706cbc402.gif)

**Comment by hungrybirder** [comment]
> > > I think this is more of a nvim-tree issue, because it resizes any other split, not just symbols-outline
> > 
> > 
> > I tested it with [nerdtree](https://github.com/preservim/nerdtree) and I got the same issue.
> 
> It works fine on nerdtree for me
> ![Peek 2021-06-28 13-14](https://user-images.githubusercontent.com/37233846/123699097-ba821e80-d813-11eb-8ce4-fdf706cbc402.gif)

Is that right? 

<img width="610" alt="iShot2021-06-29 08 54 09" src="https://user-images.githubusercontent.com/1021047/123720909-c0314000-d8b7-11eb-923b-b9bb29f39a9b.png">

<img width="602" alt="iShot2021-06-29 08 54 26" src="https://user-images.githubusercontent.com/1021047/123720931-c8897b00-d8b7-11eb-9c99-7e302ef8d837.png">

**Comment by simrat39** [comment]
@hungrybirder it seems like it happens to you on nerd tree and not me because i have `set noequalalways` in my vimrc, meanwhile nvim tree resizes splits regardless of the option. See `:h noea`.

**Comment by simrat39** [comment]
https://github.com/kyazdani42/nvim-tree.lua/blob/master/lua/nvim-tree/view.lua#L282 here's the culprit

**Comment by tuckerrc** [comment]
You should be able to lock the width of the symbols outline buffer with `winfixwidth` ([nvim help](https://neovim.io/doc/user/options.html#'winfixwidth'))

**Comment by simrat39** [comment]
> You should be able to lock the width of the symbols outline buffer with `winfixwidth` ([nvim help](https://neovim.io/doc/user/options.html#'winfixwidth'))

Thanks for the pointer! It works now
