### ISSUE TITLE
highlights

### ISSUE THREAD

**Issue by horseinthesky** [simrat39/symbols-outline.nvim#34]
Hello.
Thank you for the great plugin.

I have is a pretty unpleasant view in floating window
![image](https://user-images.githubusercontent.com/19948672/124377345-294bf580-dcb4-11eb-856c-28efb926e0a7.png)

The only option related to highlighting I've found is FocusedSymbol
https://github.com/simrat39/symbols-outline.nvim/blob/e03a9aee809f20591a0668141694e822eee4954f/lua/symbols-outline/ui.lua#L42

Is it possible to control floating window background for this plugin?

**Comment by simrat39** [comment]
Yes it is possible. The floating windows follow the `NormalFloat` highlight group.

**Comment by horseinthesky** [comment]
@simrat39 Great! Thanks a lot.
