### ISSUE TITLE
Failed to call `focusable_float`

### ISSUE THREAD

**Issue by Alienover** [simrat39/symbols-outline.nvim#36]
### NeoVim version
![image](https://user-images.githubusercontent.com/12182069/125190183-5da05280-e26e-11eb-8f94-a94b97a57ac8.png)

### Issue
When I triggered the `hover symbol` manually, the console was printing the function call failure which said the `focusable_float` does not exist. The error message is attached.
![image](https://user-images.githubusercontent.com/12182069/125190143-28940000-e26e-11eb-9366-231071e42011.png)

The weird thing is when I was hovering on the symbol, the auto preview could work.
![image](https://user-images.githubusercontent.com/12182069/125190283-e7e8b680-e26e-11eb-8f18-c9462acbac80.png)

**Comment by whot** [comment]
confirmed wfm now, thank you!

**Comment by Alienover** [comment]
Cool. WFM too.
Thx for the reply!
