### ISSUE TITLE
Option to hide some symbols.

### ISSUE THREAD

**Issue by ok97465** [simrat39/symbols-outline.nvim#38]
Hello. 
I want to see a few symbols(function, class, method) in SymbolsOutline.
Is there the option to hide symbols that I don't want?

thanks.

**Comment by simrat39** [comment]
symbol_blacklist = {} in your config (see the readme for more details)
possible values are here: https://github.com/simrat39/symbols-outline.nvim/blob/master/lua/symbols-outline/symbols.lua#L5

so if you want to hid enums for example, do

symbol_blacklist = {"Enum"}
