### ISSUE TITLE
Add a help file 

### ISSUE THREAD

**Issue by lucc** [simrat39/symbols-outline.nvim#39]
The only documentation is in the readme.  I have the plugin installed and could not remember some keybinding or command name. I then had to find the installed repository in the directory of my package manager and look at the markdown readme in nvim.

It would be nice to have a proper vim help file that can be used with `:help`.

(In my opinion the readme is a place to advertise and describe the plugin, maybe also give installatino instructions. But the main documentation should be in a help file because that is what we are used to in (n)vim and also because it is not interesting for a new user/passer by who just wants to know what the project is about.)

**Comment by simrat39** [comment]
You're right, I should make a help file. I've never written one before but i'll get to it sometime soon.
