### ISSUE TITLE
Make fixed window width optional

### ISSUE THREAD

**Issue by vicecaycedo** [simrat39/symbols-outline.nvim#40]
The symbols in the files I work in are usually quite long so I tend to make the symbols outline equal width as the other windows (`<C-w>=`).

Since 0868b5f463e9faa8aadad0c0e5e3b8edb7e5da5a makes the window fixed width, this no longer works (`:h <CTRL-W_=`).

Even better would be an option to configure the default size.

Thanks!

**Comment by simrat39** [comment]
260227983a013d1b5f7acad3d224d7fbf742c8ec

**Comment by simrat39** [comment]
This size is relative to the current split, let me know if you still want the fixed width as optional
