### ISSUE TITLE
highlight_hovered_item only working on first open

### ISSUE THREAD

**Issue by vicecaycedo** [simrat39/symbols-outline.nvim#41]
When I first open the symbol outline, the currently hovered symbol is correctly highlighted in the outline view but not the code. Similarly, once I select a symbol and move in the code, the symbol outline does not highlight anything.

Working in a python file using builtin LSP and Treesitter. Happy to provide any additional debug info that could be helpful.

**Comment by simrat39** [comment]
The highlighting is updated on the CursorHold autocommand, so try leaving your cursor on a symbol (in the code) for a second or two and it should highlight it in the outline

**Comment by vicecaycedo** [comment]
It's working - it was just some config issue. My apologies.
