### ISSUE TITLE
[bug report] the connecting line is not vertical.

### ISSUE THREAD

**Issue by cstsunfu** [simrat39/symbols-outline.nvim#42]
I use the configure of the readme, but the connecting line is not vertical.

![image](https://user-images.githubusercontent.com/24812659/127187552-151746c9-69c9-435c-a3c5-99d68f065a91.png)

**Comment by simrat39** [comment]
This is because the "Comment" highlight group is used for the lines but your colorscheme makes the comments italic, I think I should link the comment to a new highlight and remove all the italics and bold stuff

**Comment by simrat39** [comment]
It should be fixed now, please let me know if you have any issues with it
