### ISSUE TITLE
Markdown support.

### ISSUE THREAD

**Issue by cstsunfu** [simrat39/symbols-outline.nvim#43]
This is an awesome plugin, thanks for your contribution.

Markdown is a very general file type that does not have an LSP.  So would this plugin support markdown outline buildin as vista.nvim?

**Comment by simrat39** [comment]
That is a good idea, I will work on it sometime soon

**Comment by simrat39** [comment]
![image](https://user-images.githubusercontent.com/37233846/127782946-624128c0-3a23-4792-8716-033222ea73fd.png)
Here's how it looks

**Comment by Iron-E** [comment]
Is it possible to use the outline guides for that? i.e.

```
rust-tools.nvim
├ Prerequisites
└ Installation
Configuration + Functionality
├ Setup H2:34
├ Commands H2:42
├ Standalone File Support H2:61
├ Debugging H2:68
│ ├ RustDebuggables H3:79
│ ├ Hover Range H3:251
│ ├ Open Cargo.toml H3:259
│ ├ Parent Module H3:267
│ ├ Join Lines H3:275
│ └ View crate graph H3:283
├ Related Projects H2:290
└ Inspiration H2:293
```

**Comment by simrat39** [comment]
> Is it possible to use the outline guides for that? i.e.
> 
> ```
> rust-tools.nvim
> ├ Prerequisites
> └ Installation
> Configuration + Functionality
> ├ Setup
> ├ Commands
> ├ Standalone File Support
> ├ Debugging
> │ ├ RustDebuggables
> │ ├ Hover Range
> │ ├ Open Cargo.toml
> │ ├ Parent Module
> │ ├ Join Lines
> │ └ View crate graph
> ├ Related Projects
> └ Inspiration
> ```
> 
> If not, dw about it. Just wondering

This shoudn't be too hard to implement, i'll reopen this issue till I get to it
