### ISSUE TITLE
No indentation when using pylsp

### ISSUE THREAD

**Issue by Hubro** [simrat39/symbols-outline.nvim#48]
I'm using [python-lsp-server through nvim-lspconfig](https://github.com/neovim/nvim-lspconfig/blob/master/CONFIG.md#pylsp).

Fresh install of symbols-outline.nvim, I get no indentations in the outline window:

![image](https://user-images.githubusercontent.com/597206/128093249-f0bdf738-3363-49b6-8c06-10dd80f96b14.png)

The same is true for [yang-lsp](https://github.com/theia-ide/yang-lsp) (custom LSP config):

![image](https://user-images.githubusercontent.com/597206/128093605-409a1b3f-6598-4159-b7c0-cb47ad9cabb6.png)

However, indentation works for some other LSP servers, like [robotframework-lsp](https://github.com/robocorp/robotframework-lsp), so it's not a font issue.

Any ideas?

**Comment by simrat39** [comment]
This is a language server limitation. You can read more here: https://microsoft.github.io/language-server-protocol/specification#textDocument_documentSymbol

For python, try pyright as that supports the newer, nested symbols data.

**Comment by Hubro** [comment]
Thanks

**Comment by dsully** [comment]
The pylsp folks say they support textDocument/documentSymbol. 

See https://github.com/python-lsp/python-lsp-server/issues/74

**Comment by simrat39** [comment]
> The pylsp folks say they support textDocument/documentSymbol.
> 
> See [python-lsp/python-lsp-server#74](https://github.com/python-lsp/python-lsp-server/issues/74)

Atleast in my testing, it still does not give a hierarchy. Anyways whenever it will for us, it will automatically work because DocumentSymbol[] is supported and we aren't doing anything special for pylsp

**Comment by dsully** [comment]
Yep, the same with my testing. Also agreed that it should work if the server is sending the right response.

Any chance you could post on the python-lsp-server#74 thread? Something isn't quite right here.

**Comment by ok97465** [comment]
![a](https://user-images.githubusercontent.com/22970578/134768810-b34a45e8-4f45-4a61-9d42-2605ca00c95d.png)

The responses of pylsp and pyright are different for the above code.

For pyright's response, the symbols-outline operate normally.

The pylsp use "containerName" for hierarchy and the pyright use "children" for hierarchy.

-- pyright response
```
{
		["result"] = 
		{
			[1] = 
			{
				["selectionRange"] = 
				{
					["end"] = 
					{
						["line"] = 3,
						["character"] = 10,
					},
					["start"] = 
					{
						["line"] = 3,
						["character"] = 6,
					},
				},
				["kind"] = 5,
				["children"] = 
				{
					[1] = 
					{
						["selectionRange"] = 
						{
							["end"] = 
							{
								["line"] = 6,
								["character"] = 12,
							},
							["start"] = 
							{
								["line"] = 6,
								["character"] = 8,
							},
						},
						["kind"] = 6,
						["children"] = 
						{
						},
						["name"] = "foo1",
						["range"] = 
						{
							["end"] = 
							{
								["line"] = 8,
								["character"] = 12,
							},
							["start"] = 
							{
								["line"] = 6,
								["character"] = 4,
							},
						},
					},
				},
				["name"] = "Data",
				["range"] = 
				{
					["end"] = 
					{
						["line"] = 8,
						["character"] = 12,
					},
					["start"] = 
					{
						["line"] = 3,
						["character"] = 0,
					},
				},
			},
		},
	}
```

-- pyslp response
```
{
		["result"] = 
		{
			[1] = 
			{
				["location"] = 
				{
					["uri"] = "file:///home/ok97465/kk/a.py",
					["range"] = 
					{
						["end"] = 
						{
							["line"] = 9,
							["character"] = 0,
						},
						["start"] = 
						{
							["line"] = 3,
							["character"] = 0,
						},
					},
				},
				["name"] = "Data",
				["kind"] = 5,
			},
			[2] = 
			{
				["location"] = 
				{
					["uri"] = "file:///home/ok97465/kk/a.py",
					["range"] = 
					{
						["end"] = 
						{
							["line"] = 9,
							["character"] = 0,
						},
						["start"] = 
						{
							["line"] = 6,
							["character"] = 4,
						},
					},
				},
				["kind"] = 6,
				["name"] = "foo1",
				["containerName"] = "Data",
			},
		},
	},
```
