### ISSUE TITLE
Outline popup (with floating window)

### ISSUE THREAD

**Issue by Hubro** [simrat39/symbols-outline.nvim#51]
My main use case of an outline view is to navigate to a different position in large files. I usually:

- Open outline window
- Scroll down/up a bit, or use `/`, to find the symbol I'm looking for
- Press enter on an item to jump there
- Close the outline

For this workflow, it would be a big user experience upgrade if it was possible to launch the outline window as a Neovim floating window on top of the current buffer, then automatically close it when I press enter on a symbol.

Would this be possible to achieve now with a bit of advanced configuration? Or would it require additions to the plugin?

**Comment by simrat39** [comment]
Just use telescope for this usecase, they support lsp symbols

**Comment by Hubro** [comment]
I didn't know that. I gave that a shot now, and it's not really a comparable experience...

There are no icons, there is no indentation, it spawns a gigantic window, it includes an unnecessary preview window, it includes *variables* and I don't see a way to disable that.

![image](https://user-images.githubusercontent.com/597206/128612721-65c27cc0-10e1-4d8a-8386-e35ec238c750.png)

![image](https://user-images.githubusercontent.com/597206/128612872-fcc0da34-c690-442b-ae1d-21f02dc71e5c.png)

**Comment by Hubro** [comment]
After some more research, Telescope seems more hackable than I first thought. I have gotten the outline popup to a pretty decent place:

![image](https://user-images.githubusercontent.com/597206/128613975-8c831901-7387-4ee6-95b1-692292414fa5.png)

But it's still lacking indentation and icons, so it's nowhere near as pleasing to the eye as this plugin :disappointed:

**Comment by simrat39** [comment]
TBH this plugin is just not for your workflow, at most i could add a mapping to goto the symbols location and then close the outline, but opening the outline in a floating window is out of the scope of this plugin

**Comment by dccsillag** [comment]
Hello @simrat39,

Why exactly is this outside of this plugin's scope? Wouldn't it be just a matter of abstracting the window opening and closing logic a bit?

(I'm open to doing a PR for this.)
