### ISSUE TITLE
Document highlight groups

### ISSUE THREAD

**Issue by ldelossa** [simrat39/symbols-outline.nvim#52]
Hey there, 

Great plugin but it looks terrible with my theme @ http://www.github.com/ldelossa/vimdark

Can you export the highlight groups? 

Here is a screen shot of it looking bad. 

![Screenshot from 2021-08-08 13-36-11](https://user-images.githubusercontent.com/5642902/128640635-8babdcbc-dc09-49c8-bd75-3f7962e5e5cd.png)

**Comment by simrat39** [comment]
Thanks for the issue, i'll add them to the readme soon

**Comment by simrat39** [comment]
Ill make more of these configurable in the future
