### ISSUE TITLE
Preview seems to be interfering with <C-w><C-w>

### ISSUE THREAD

**Issue by jeanlucthumm** [simrat39/symbols-outline.nvim#53]
Open the outline in a single buffer view. If you do `<C-w><C-w>` fast enough it switches focus back and forth as expected. But if you are currently focused on the outline, and you let the preview window come up, then `<C-w><C-w>` seems to just close the preview window but the focus stays on the outline.

**Comment by simrat39** [comment]
This happens because the preview is a window, so c-w c-w switches to that window, but we don't allow that window being in focus so we close it, which shifts the focus back to the outline. You can use c-w h/l to move focus.
