### ISSUE TITLE
Possible for node to be nil

### ISSUE THREAD

**Issue by rockerBOO** [simrat39/symbols-outline.nvim#60]
https://github.com/simrat39/symbols-outline.nvim/blob/40b7d5cbaa51c031061827c48e6a05748db7e91d/lua/symbols-outline.lua#L114

```
E5108: Error executing lua ...acker/start/symbols-outline.nvim/lua/symbols-outline.lua:116: attempt to in
dex local 'node' (a nil value)
````

**Comment by simrat39** [comment]
It shouldn't be nil normally, what lsp do you get this with? Also any reproducible example?

**Comment by rockerBOO** [comment]
I think it might be related to the LSP not initializing properly and getting stuck. (lua-langugage-server was getting stuck pinning at 100% CPU).

Doesn't happen now that I have updated it. Feel free to close if this is adequate.

I suppose most people wont run into this but it could be possible if the state hasn't populated it will error.

**Comment by simrat39** [comment]
i'll close it for now then, lets see if others get it or not and then we can add a null check.
