### ISSUE TITLE
The icons set in the init.lua may not be correct.

### ISSUE THREAD

**Issue by csy19960309** [simrat39/symbols-outline.nvim#67]
This is what I see in the web browser.
![屏幕截图(32)](https://user-images.githubusercontent.com/12546423/134790650-5ba11277-8f6e-4ca6-b415-e34cad7c46c8.png)

And this is what I see in the Windows Terminal.
![屏幕截图(33)](https://user-images.githubusercontent.com/12546423/134790679-d5b8ab1e-c1d4-4f2d-8850-5eb8a7a41219.png)

Thus when in use it provides me with icons which are squares filled with a question mark.

**Comment by ram02z** [comment]
The squares filled with a question marks are because the glyphs are misisng from your font. Use a [nerd font](https://www.nerdfonts.com/) with windows terminal instead.

**Comment by csy19960309** [comment]
> The squares filled with a question marks are because the glyphs are misisng from your font. Use a [nerd font](https://www.nerdfonts.com/) with windows terminal instead.

Thanks a lot, it worked!

**Comment by tonyma** [comment]
I installed FiraCode Nerd Font but icons still aren't displayed.
@csy19960309  which font did you use?
![image](https://user-images.githubusercontent.com/4219509/147892544-600cd57e-875e-4a21-a062-f78f3af5e55f.png)
![image](https://user-images.githubusercontent.com/4219509/147892566-c8d715df-cf22-4e37-b40a-f56cda45a8c8.png)
