### ISSUE TITLE
[Bug]: markdown: the plugin takes `comment` in `code block` as `headings`

### ISSUE THREAD

**Issue by younger-1** [simrat39/symbols-outline.nvim#69]
The `symbols-outline` can't recognize the `comment`  in `code block` in md files. It takes them as md `headings` instead. 

eg. `symbols-outline` takes `# clone it` in `sh code block`  as `Heading level 1`.
![symbol](https://user-images.githubusercontent.com/45989017/136178990-9e6c6064-82d2-47d4-89d2-349ec2a721d1.png)

[vista](https://github.com/liuchengxu/vista.vim) can handle this situation correctly.
![vista](https://user-images.githubusercontent.com/45989017/136179199-33669cea-0415-4126-a185-1a80b018132f.png)

Is it possible to achieve it with `symbols-outline` for md files? If it's painful to fix then feel free to close this issue.

**Comment by simrat39** [comment]
Fixed. Do you think we should have a separate entry for code blocks?

**Comment by younger-1** [comment]
Oh, it will be great to provide this function with keymapping to toggle it in `symobols-outline` view.

Another question, I would like to know if there is a way to display the headings with indent guides in `symobols-outline` view in md files, just like in lua files. 

Images below show the case. Instead of displaying ` ### Parser`, displaying `3️`(other `H3` font-icons) with indent guides may be more conciser. And it would be great to highlight all the parent nodes like in lua files.
`.md`:
![图片](https://user-images.githubusercontent.com/45989017/136324057-fa189046-1d18-4d32-8a4a-b0274f6d4ef9.png)
`.lua`:
![图片](https://user-images.githubusercontent.com/45989017/136323920-ee223f1a-5d85-4e11-972a-7d088d7debb0.png)

**Comment by simrat39** [comment]
> And more generally, it will be awesome to provide a `filter` to only show target entries in `symobols-outline` view, so it is possible for users to found out(and then navigate to) their interested entries which belong to certain symbol catagories like `Class`, `Method`, `Field`. `Filter` can also be one **and/or** more other predefined/user-defined functions.

you can use the symbol_blacklist table in the config to hide certain type of symbols
