### ISSUE TITLE
[Question] Folding

### ISSUE THREAD

**Issue by manikandanraji** [simrat39/symbols-outline.nvim#7]
Is there any keymap which I can use to fold functions? By default, it lists all the symbols. I would like to have a functionality where we can fold and unfold the selected symbol.

**Comment by simrat39** [comment]
> Is there any keymap which I can use to fold functions? By default, it lists all the symbols. I would like to have a functionality where we can fold and unfold the selected symbol.

Folding is not supported as of now, but is planned for the future. Will keep this issue open till it is implemented

**Comment by elliothatch** [comment]
I've implemented a simple vimscript fold-expr for this plugin, which just looks at the position of the last "pipe" character indicating a symbol (├ or └), and then sets the fold level based on its column position. To include the parent symbol in the same fold it also performs the check on the next line and uses that value if it's greater.

Kind of hacky, but it works at least on the files I've tested. Maybe will be useful to people waiting for official folding support.

Full code below for the fold-expr and an autocmd to enable it on the Outline filetype buffer.

```
function! FoldOutline(lnum)
	let l:line = getline(v:lnum)
	let l:nextline = getline(v:lnum + 1)

	let l:linelevel = (matchstrpos(l:line,  '.*[├└]')[2] - 2)/4 + 1
	let l:nextlinelevel = (matchstrpos(l:nextline,  '.*[├└]')[2] - 2)/4 + 1

	if l:nextlinelevel > l:linelevel
		return l:nextlinelevel
	endif

	return l:linelevel
endfunction

autocmd FileType Outline execute 'setl foldlevel=1|setl foldexpr=FoldOutline(v:lnum)|setl foldmethod=expr'
```

**Comment by eddiebergman** [comment]
Removing guides and just using `foldmethod=indent` works extremely well too

**Comment by simrat39** [comment]
https://github.com/simrat39/symbols-outline.nvim/pull/142 Folding support has been added
