### ISSUE TITLE
Doesn't open with recent changes

### ISSUE THREAD

**Issue by arodland** [simrat39/symbols-outline.nvim#74]
Worth noting that I don't use coc or have it installed. When I run `SymbolsOutline` or `SymbolsOutlineOpen` on latest master, nothing at all happens... no error, just nothing.

Git bisect shows that commit 28c5b0513a9da37b1842a16184555a041eb4b72d was the last good one; all commits starting with a0d563172dc0818a62ebd836c363268c3c45bd35 are bad.

**Comment by simrat39** [comment]
Which language server? nvim version?

**Comment by arodland** [comment]
Nvim is 0.6-latest git. I've seen the problem with several language servers that used to work (every one I've tried). Gopls and pylsp for certain.

**Comment by simrat39** [comment]
> Nope, it doesn't appear to be that. If I change `ipairs` to `pairs` at nvim-lsp.lua line 14 it does work. My lua-fu is weak, but a stackoverflow answer I ran into says "`ipairs` only works on tables which have an element with the key 1". And that does seem to be the culprit; if I `lua print vim.inspect(vim.lsp.buf_get_clients())` the table has one element with the key _2_.

I see. Odd that it works for me, probably some lua version mismatch. I'll apply your change
