### ISSUE TITLE
I cannot set symbol outline on the left

### ISSUE THREAD

**Issue by nyngwang** [simrat39/symbols-outline.nvim#76]
I saw an old issue saying that he cannot set it to the right. OK so now I cannot set it to the left :/

**Comment by simrat39** [comment]
Ah this is some funky stuff with splitirght. I think I can fix it

**Comment by simrat39** [comment]
Actually it seems like its fine with nosplitright/splitright so that's not it. Do you have a reproducible config?

**Comment by nyngwang** [comment]
I think this can be closed now because I have uninstalled it after experiencing some delay on a large project...
