### ISSUE TITLE
Fix icon coloring

### ISSUE THREAD

**Issue by dccsillag** [simrat39/symbols-outline.nvim#78]
Here is the current source for `highlight_text` in `ui.lua`:

```lua
local function highlight_text(name, text, hl_group)
    vim.cmd(string.format("syn match %s /%s/", name, text))
    vim.cmd(string.format("hi def link %s %s", name, hl_group))
end
```

This implementation might work when you use icon characters, but it's extremely fragile (besides not working if you use plain text as "icons").

Here are some issues with it:

- There may be conflicts with the highlights; for example, what highlight is going to be used for the `Function` icon? Well, it's the `Function` highlight, since that's that icon's `name`. But `Function` is already used by Vim's syntax highlighting! That means that those highlights must be the same, which is bad for customizability.
- The icon's text is used as a regular expression for the highlight. This is a *really bad idea*. For example, do try to set `[FUNC]` as an icon, and see what happens -- especially if your function is named, for example, `myFunction`.

A *much* better way to do this would be to use `matchaddpos` or `nvim_buf_add_highlight` to set the highlights in `parse_and_write`. The main bit would be in `write_outline`, but we would need to tweak `get_lines` a bit to generate the information of where the icon is.

If you want, I can do a PR implementing what I just described above.

**Comment by simrat39** [comment]
That ui stuff was written when we couldn't customize the icons, but yeah youre right we should use proper range based highlighting for that. Feel free to open a PR
