### ISSUE TITLE
colorscheme/symbols don't seem to work

### ISSUE THREAD

**Issue by cetanu** [simrat39/symbols-outline.nvim#80]
Hello there,

My apologies for bringing what is probably a trivial issue here, but I was wondering if you knew offhand why it would be the case that my colorscheme doesn't seem to map to the symbols-outline window, or why there are no characters to represent each symbols type?

I've only added the plugin + the config snippet that is found in the readme of this project

Am I missing some dependency/plugin?

![image](https://user-images.githubusercontent.com/2289018/142520447-d6192fef-843d-4782-bfeb-546bc18d408f.png)

**Comment by simrat39** [comment]
Do the icons render in your config? Also, the highlights used are from TreeSitter so make sure your colorscheme supports tree sitter

**Comment by cetanu** [comment]
Hmm I think it's my terminal, or my fonts not rendering properly.
I tried on a Linux machine and it works just fine. On my Macbook, not so much.
