### ISSUE TITLE
Filetype unknown

### ISSUE THREAD

**Issue by tynguyen2k1** [simrat39/symbols-outline.nvim#81]
I get the following message every time I start symbols-outline.nvim
![Screenshot_20211121_133852](https://user-images.githubusercontent.com/64082226/142752492-7db87941-e116-4992-aa40-a28e7101221e.png)
`configuration:` default
`NVIM:` v0.5.1

**Comment by simrat39** [comment]
This isn't by this plugin, must be some other plugin which is doing this

**Comment by predmijat** [comment]
Hi,

I'm also getting "filetype unknown" as soon as preview is displayed and I'm not sure what is responsible...any ideas?

**Comment by jeeeem** [comment]
I also have this error whenever I tried to preview the symbols.

**Comment by Ruixi-rebirth** [comment]
> I get the following message every time I start symbols-outline.nvim ![Screenshot_20211121_133852](https://user-images.githubusercontent.com/64082226/142752492-7db87941-e116-4992-aa40-a28e7101221e.png) `configuration:` default `NVIM:` v0.5.1

**I have the same problem, have you solved it?**

**Comment by LVvVQ** [comment]
@simrat39 I had the same problem, so I looked at the plugin's source code and I found that I commented a few places in it and the problem went away, so why is it not the plugin's problem? This file is located at ~/.local/share/nvim/site/pack/packer/start/symbols-outline.nvim/lua/symbols-outline/preview.lua
![2022-04-25_195723](https://user-images.githubusercontent.com/56420931/165084625-c3fe864f-04ed-4473-b053-88acc6f83225.jpg)
