### ISSUE TITLE
Markdown file produces error "method textDocument/hover is not supported by any of the servers registered for the current buffer"

### ISSUE THREAD

**Issue by benfrain** [simrat39/symbols-outline.nvim#82]
I am after something to give me an outline of long markdown documents – this plugin looks like exactly what I am after, thanks! 

Just installed but when I use the outline to move around the document I get this error:

`Error detected while processing CursorHold Autocommands for "<buffer=4>":
method textDocument/hover is not supported by any of the servers registered for the current buffer`

I don't have a specific LS installed for markdown, which I suspect is the reason for the error? However, perhaps a warning here may be better as when I clear the Error it seems to jump to the intended place (with this error I have to quit nvim and restart).

**Comment by simrat39** [comment]
Looks like you have a language server which attaches to markdown files, but doesn't provide hover info ( which is needed for the preview thingies ). To fix this we should check if the language server supports hover before making the request. I'll get it fixed soon, thanks for the report. For a temp fix you might wanna not have that lsp attach to markdown files.

**Comment by benfrain** [comment]
Great, thanks. It’s actually ‘null-ls’ at the minute which attaches to do formatting of the buffer via ‘prettier’.

**Comment by simrat39** [comment]
@benfrain it should be fixed now

**Comment by benfrain** [comment]
@simrat39 thanks, works great.
