### ISSUE TITLE
Cannot execute SymbolOutline,SymbolOutlineOpen

### ISSUE THREAD

**Issue by ruanyouxing** [simrat39/symbols-outline.nvim#85]
i tried to type :SymbolOutlineOpen and :SymbolOutline in command mode but it just dumped and showed nothing,
Can you help this?

**Comment by zhouguannan** [comment]
me too

**Comment by simrat39** [comment]
Do you have a lsp / coc running?

**Comment by ruanyouxing** [comment]
it shows an error

**Comment by ruanyouxing** [comment]
![error.png](https://user-images.githubusercontent.com/87190231/144787998-c6b6857a-7bff-42cf-9941-1f02b0d3a3c1.png)

**Comment by ruanyouxing** [comment]
i use coc tho

**Comment by simrat39** [comment]
uhh so we need to check if coc is ready, i'll see if there is a way to do that

**Comment by simrat39** [comment]
ok so it's the global variable coc_service_initialized it seems
https://github.com/neoclide/coc.nvim/blob/94fb1527f4be1b499029ef76cb90e73a384d063f/plugin/coc.vim#L72

**Comment by simrat39** [comment]
Should be fixed now, please test it and let me know

**Comment by ruanyouxing** [comment]
Thanks it worked
