### ISSUE TITLE
Multiple LSP clients

### ISSUE THREAD

**Issue by ReubenM** [simrat39/symbols-outline.nvim#9]
For python I'm using both pyls and jedi-language-server. As seen in #5 pyls does not excel in this area, but I would prefer Jedi for symbols anyway.

Need some options to blacklist/whitelist/mask/whatever which LSP client(s) to use.

**Comment by simrat39** [comment]
@ReubenM I tested with pyls and pyright, let me know how it works for you now so that we can close this issue.

 (you can find the instructions in the readme for setting a blacklist)

**Comment by duikboot** [comment]
I checked out the commit, but it doesn't work for me, I get to outline buffers. One filled and one empty. 

    local opts = {
      -- whether to highlight the currently hovered symbol
      -- disable if your cpu usage is higher than you want it
      -- or you just hate the highlight
      -- default: true
      highlight_hovered_item = true,

      -- whether to show outline guides
      -- default: true
      show_guides = true,
      lsp_blacklist = {'pyls'}
    }

    require('symbols-outline').setup(opts)

**Comment by simrat39** [comment]
@duikboot could be because the way to configure the plugin has changed. You no longer need to call setup, it is already called. To configure the plugin, do this

vim.g.symbols_outline = {
    lsp_blacklist = { "pyls" }
}

(Other options are automatically set to the defaults)

**Comment by duikboot** [comment]
It works for me now, Thanks a lot!
