### ISSUE TITLE
Doesn't work with multi-filetypes. 

### ISSUE THREAD

**Issue by fullstopslash** [simrat39/symbols-outline.nvim#90]
I have a really niche use case here. Both Vim and Neovim have a handy feature that allows a file to be recognized as multiple filetypes, then various scripts and autogroup actions can be ran for each of the filetypes that applies. As an example I'm using the [Vimwiki](https://github.com/vimwiki/vimwiki) plugin to edit markdown files, some types of markdown can also be considered a pandoc file as well.  In neovim if I open a markdown file and issue the command `:set filetype` it shows the current filetype as `vimwiki.markdown.pandoc` as expected. However, this plugin doesn't recognize this as a list of filetypes. Instead, as far as I can tell, it recognizes a single filetype `vimwiki.markdown.pandoc` and doesn't open.  For reference both [Tagbar](https://github.com/preservim/tagbar) and [Vista.vim](https://github.com/liuchengxu/vista.vim) work out of the box in recognizing the markdown structure in this case. At any rate, thanks again for this rad plugin!

**Comment by dominikb1888** [comment]
I am on MacOS and neovim and for me ":set filetype?" shows only vimiwiki or pandoc w/o any reference to markdown. The committed regex does not match on this. Happy to test and supply a working version.
