### ISSUE TITLE
Is it support to auto close symbols-outline window when it is the last window?

### ISSUE THREAD

**Issue by gh-liu** [simrat39/symbols-outline.nvim#93]

**Comment by DRogueRonin** [comment]
I tried something similar to NERDTree ([ref](https://github.com/preservim/nerdtree#how-can-i-close-vim-or-a-tab-automatically-when-nerdtree-is-the-last-window)).
But first I needed the state, so I wrote a function that sets it to a global variable.

Here's the whole script:

```vim
lua <<EOF
set_symbols_outline_state = function()
  vim.g['symbols_outline_state'] = require('symbols-outline').state
end
EOF

autocmd BufEnter * :lua set_symbols_outline_state()
autocmd BufEnter * if winnr('$') == 1 && exists('g:symbols_outline_state.outline_buf') && g:symbols_outline_state.outline_buf | quit | endif
```

But it would certainly be nice to have the state already available or some user-facing function to check whether the buffer is still open.

**Comment by gh-liu** [comment]
THX.
