### ISSUE TITLE
Slow on large file

### ISSUE THREAD

**Issue by glyh** [simrat39/symbols-outline.nvim#95]
I have a 400-lines lua config for neovim, when I try to generate symbols-outlines for it, it tooks quite a few seconds.

**Comment by glyh** [comment]
OK this might be some other plugins related, let me try to find some minimal config to reproduce this

**Comment by glyh** [comment]
I found that this is caused by color scheme. So I'll close this and open an issue in other place.

**Comment by Realtyxxx** [comment]
老哥后面怎么解决的啊，我的symbols-outline 打开 lua的时候很慢
