### ISSUE TITLE
Error when using `[]` as symbol icon

### ISSUE THREAD

**Issue by fenuks** [simrat39/symbols-outline.nvim#99]
I have set `Array = {icon = "[]", hl = "TSConstant"},` (pair of plain ASCII square brackets) as one of the custom symbols which results in
```
Error executing vim.schedule lua callback: .../plugged/symbols-outline.nvim/lua/symbols-outline/ui.lua:25: Vim(syntax):E401: Pattern delimiter not found: /[]/
```
Probably icons need to be escaped before passed into regex.

I'm using NVIM v0.6.1.

**Comment by simrat39** [comment]
We no longer use regex based highlighting, so [] works. Closing.
